// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package handler

import (
	"net/http"

	protected "auroramihomo/backend/api/internal/handler/protected"
	public "auroramihomo/backend/api/internal/handler/public"
	"auroramihomo/backend/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPut,
				Path:    "/api/v1/adguard/auto-update",
				Handler: protected.AdGuardSetAutoUpdateHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/api/v1/adguard/boot",
				Handler: protected.AdGuardSetBootHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/api/v1/adguard/cdn",
				Handler: protected.AdGuardSetCDNHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/v1/adguard/check-update",
				Handler: protected.AdGuardCheckUpdateHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/api/v1/adguard/component",
				Handler: protected.AdGuardSetComponentHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/api/v1/adguard/credentials",
				Handler: protected.AdGuardSetCredentialsHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/v1/adguard/dns-entry-preset",
				Handler: protected.AdGuardApplyEntryDNSPresetHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/api/v1/adguard/dns-mode",
				Handler: protected.AdGuardSetDNSModeHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/api/v1/adguard/dns-port",
				Handler: protected.AdGuardSetDNSPortHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/v1/adguard/install",
				Handler: protected.AdGuardInstallHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/v1/adguard/restart",
				Handler: protected.AdGuardRestartHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/v1/adguard/start",
				Handler: protected.AdGuardStartHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/v1/adguard/status",
				Handler: protected.AdGuardStatusHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/v1/adguard/stop",
				Handler: protected.AdGuardStopHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/v1/adguard/uninstall",
				Handler: protected.AdGuardUninstallHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/api/v1/adguard/web-port",
				Handler: protected.AdGuardSetWebPortHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/v1/adguard/wiring",
				Handler: protected.AdGuardWiringHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/v1/adguard/wiring/apply",
				Handler: protected.AdGuardWiringApplyHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/v1/adguard/wiring/rollback",
				Handler: protected.AdGuardWiringRollbackHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/v1/auth/password",
				Handler: protected.ChangePasswordHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/v1/collections",
				Handler: protected.ListCollectionsHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/v1/collections",
				Handler: protected.CreateCollectionHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/api/v1/collections/:id",
				Handler: protected.UpdateCollectionHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/api/v1/collections/:id",
				Handler: protected.DeleteCollectionHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/v1/collections/:id/build",
				Handler: protected.BuildCollectionHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/v1/config/base",
				Handler: protected.GetBaseConfigHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/api/v1/config/base",
				Handler: protected.UpdateBaseConfigHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/v1/config/diff",
				Handler: protected.GetConfigDiffHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/v1/config/final",
				Handler: protected.GetFinalConfigHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/v1/config/merge",
				Handler: protected.MergeConfigHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/v1/config/pull-merge",
				Handler: protected.PullMergeConfigHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/v1/config/remote",
				Handler: protected.GetRemoteConfigHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/v1/config/unmerged",
				Handler: protected.GetConfigUnmergedHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/v1/config/versions",
				Handler: protected.ListConfigVersionsHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/v1/config/versions/:id/restore",
				Handler: protected.RestoreConfigVersionHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/v1/conflicts",
				Handler: protected.GetConflictsHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/v1/conflicts/:id/resolve",
				Handler: protected.ResolveConflictHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/v1/convert",
				Handler: protected.ConvertSubscriptionHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/v1/dashboard/entry",
				Handler: protected.DashboardEntryHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/v1/files",
				Handler: protected.ListFilesHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/v1/files",
				Handler: protected.CreateFileHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/api/v1/files/:id",
				Handler: protected.UpdateFileHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/api/v1/files/:id",
				Handler: protected.DeleteFileHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/v1/files/:id/sync",
				Handler: protected.SyncFileHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/v1/mihomo/logs",
				Handler: protected.GetMihomoLogsHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/v1/mihomo/reload",
				Handler: protected.MihomoReloadHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/v1/mihomo/restart",
				Handler: protected.MihomoRestartHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/v1/mihomo/start",
				Handler: protected.MihomoStartHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/v1/mihomo/stop",
				Handler: protected.MihomoStopHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/v1/preview",
				Handler: protected.PreviewHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/v1/settings/merge-policy",
				Handler: protected.GetMergePolicyHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/api/v1/settings/merge-policy",
				Handler: protected.PutMergePolicyHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/v1/settings/remote-source",
				Handler: protected.GetRemoteSourceHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/api/v1/settings/remote-source",
				Handler: protected.PutRemoteSourceHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/v1/settings/update",
				Handler: protected.GetUpdateSettingsHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/api/v1/settings/update",
				Handler: protected.PutUpdateSettingsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/v1/shares",
				Handler: protected.ListSharesHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/api/v1/shares/:kind/:id",
				Handler: protected.UpdateShareHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/v1/shares/:kind/:id/reset",
				Handler: protected.ResetShareHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/v1/shares/:kind/:id/revoke",
				Handler: protected.RevokeShareHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/v1/subscriptions",
				Handler: protected.ListSubscriptionsHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/v1/subscriptions",
				Handler: protected.CreateSubscriptionHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/api/v1/subscriptions/:id",
				Handler: protected.UpdateSubscriptionHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/api/v1/subscriptions/:id",
				Handler: protected.DeleteSubscriptionHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/v1/subscriptions/:id/update",
				Handler: protected.UpdateSubscriptionNowHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/v1/system/stats",
				Handler: protected.SystemStatsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/v1/system/status",
				Handler: protected.SystemStatusHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/v1/tasks",
				Handler: protected.ListTasksHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/api/v1/transparent",
				Handler: protected.PutTransparentHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/v1/transparent/confirm",
				Handler: protected.ConfirmTransparentHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/v1/transparent/provision",
				Handler: protected.ProvisionTransparentHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/v1/transparent/rules",
				Handler: protected.GetTransparentRulesHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/api/v1/transparent/rules",
				Handler: protected.UpdateTransparentRulesHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/v1/transparent/status",
				Handler: protected.GetTransparentStatusHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/v1/update/adguard",
				Handler: protected.UpdateAdGuardHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/v1/update/check",
				Handler: protected.UpdateCheckHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/v1/update/mihomo",
				Handler: protected.UpdateMihomoHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/v1/update/zashboard",
				Handler: protected.UpdateZashboardHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/v1/auth/login",
				Handler: public.LoginHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/v1/file/:token",
				Handler: public.ServeFileHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/v1/share/:token",
				Handler: public.ShareByTokenHandler(serverCtx),
			},
		},
	)
}
