// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package types

type ChangePasswordReq struct {
	OldPassword string `json:"oldPassword"`
	NewPassword string `json:"newPassword"`
}

type Collection struct {
	Id         int64              `json:"id"`
	Name       string             `json:"name"`
	Enabled    bool               `json:"enabled"`
	Operators  []PipelineOperator `json:"operators"`
	ShareToken string             `json:"shareToken"`
	SubIds     []int64            `json:"subIds"`
}

type CollectionReq struct {
	Name      string             `json:"name"`
	Enabled   bool               `json:"enabled,optional,default=true"`
	Operators []PipelineOperator `json:"operators,optional"`
	SubIds    []int64            `json:"subIds"`
}

type CollectionUpdateReq struct {
	Id        int64              `path:"id"`
	Name      string             `json:"name,optional"`
	Enabled   *bool              `json:"enabled,optional"`
	Operators []PipelineOperator `json:"operators,optional"`
	SubIds    []int64            `json:"subIds,optional"`
}

type ConfigContent struct {
	Content string `json:"content"`
}

type ConfigVersionItem struct {
	Id        int64  `json:"id"`
	Hash      string `json:"hash"`
	Note      string `json:"note"`
	CreatedAt string `json:"createdAt"`
}

type ConflictItem struct {
	Id          int64  `json:"id"`
	Key         string `json:"key"`
	Type        string `json:"type"`
	Path        string `json:"path"`
	LocalValue  string `json:"localValue"`
	RemoteValue string `json:"remoteValue"`
	ManualValue string `json:"manualValue"`
	Resolution  string `json:"resolution"`
	Resolved    bool   `json:"resolved"`
}

type ConvertReq struct {
	Url      string `json:"url,optional"`
	Content  string `json:"content,optional"`
	Template string `json:"template,optional"`
}

type ConvertResp struct {
	Format string `json:"format"`
	Yaml   string `json:"yaml"`
	Links  string `json:"links"`
	Count  int    `json:"count"`
}

type CreateSubscriptionReq struct {
	Name      string             `json:"name"`
	Url       string             `json:"url,optional"`
	Content   string             `json:"content,optional"`
	UserAgent string             `json:"userAgent,optional"`
	Enabled   bool               `json:"enabled,optional,default=true"`
	Interval  int                `json:"interval,optional,default=3600"`
	Operators []PipelineOperator `json:"operators,optional"`
}

type DashboardEntryResp struct {
	Available bool   `json:"available"`
	Url       string `json:"url"`
	Host      string `json:"host"`
	Port      string `json:"port"`
	Message   string `json:"message"`
}

type DiffItem struct {
	Kind string `json:"kind"`
	Name string `json:"name"`
	From string `json:"from,optional"`
	To   string `json:"to,optional"`
}

type DiffReport struct {
	Added   []DiffItem `json:"added"`
	Removed []DiffItem `json:"removed"`
	Changed []DiffItem `json:"changed"`
}

type FileTokenReq struct {
	Token string `path:"token"`
}

type IdPathReq struct {
	Id int64 `path:"id"`
}

type LogLine struct {
	Time    string `json:"time"`
	Stream  string `json:"stream"`
	Message string `json:"message"`
}

type LoginReq struct {
	Password string `json:"password"`
}

type LoginResp struct {
	Token string `json:"token"`
}

type MergePolicyReq struct {
	ProxyPriority   string `json:"proxyPriority,optional"`
	RulePriority    string `json:"rulePriority,optional"`
	DNSPriority     string `json:"dnsPriority,optional"`
	TUNPriority     string `json:"tunPriority,optional"`
	GeneralPriority string `json:"generalPriority,optional"`
}

type MergePolicyResp struct {
	ProxyPriority   string `json:"proxyPriority"`
	RulePriority    string `json:"rulePriority"`
	DNSPriority     string `json:"dnsPriority"`
	TUNPriority     string `json:"tunPriority"`
	GeneralPriority string `json:"generalPriority"`
}

type MergeResultEx struct {
	Success       bool   `json:"success"`
	Message       string `json:"message"`
	ConflictCount int    `json:"conflictCount"`
}

type PipelineOperator struct {
	Type    string `json:"type"`
	Enabled bool   `json:"enabled"`
	Payload string `json:"payload"` // Raw JSON string to bypass map[string]interface{} limits in goctl
}

type PreviewReq struct {
	Kind               string             `json:"kind"`
	Target             string             `json:"target,optional"`
	Operators          []PipelineOperator `json:"operators,optional"`
	Url                string             `json:"url,optional"`
	Content            string             `json:"content,optional"`
	UserAgent          string             `json:"userAgent,optional"`
	SubIds             []int64            `json:"subIds,optional"`
	ConfigType         string             `json:"configType,optional"`
	SourceMode         string             `json:"sourceMode,optional"`
	SyncUrl            string             `json:"syncUrl,optional"`
	MergeSources       string             `json:"mergeSources,optional"`
	IgnoreFailedRemote string             `json:"ignoreFailedRemote,optional"`
	SourceType         string             `json:"sourceType,optional"`
	SourceId           int64              `json:"sourceId,optional"`
	TemplateLang       string             `json:"templateLang,optional"`
}

type PreviewResp struct {
	Format    string   `json:"format"`
	Original  string   `json:"original"`
	Processed string   `json:"processed"`
	Count     int      `json:"count"`
	Warnings  []string `json:"warnings"`
}

type RemoteSourceOption struct {
	Type     string `json:"type"`
	Id       int64  `json:"id"`
	Name     string `json:"name"`
	Disabled bool   `json:"disabled"`
	Reason   string `json:"reason"`
}

type RemoteSourceReq struct {
	SourceType  string `json:"sourceType,optional"`
	SourceId    int64  `json:"sourceId,optional"`
	SourceUrl   string `json:"sourceUrl,optional"`
	Cron        string `json:"cron,optional"`
	CronEnabled *bool  `json:"cronEnabled,optional"`
}

type RemoteSourceResp struct {
	SourceType  string               `json:"sourceType"`
	SourceId    int64                `json:"sourceId"`
	SourceUrl   string               `json:"sourceUrl"`
	Cron        string               `json:"cron"`
	CronEnabled bool                 `json:"cronEnabled"`
	Options     []RemoteSourceOption `json:"options"`
}

type ResolveConflictReq struct {
	Id          int64  `path:"id"`
	Resolution  string `json:"resolution"`
	ManualValue string `json:"manualValue,optional"`
}

type Result struct {
	Success bool   `json:"success"`
	Message string `json:"message"`
}

type ShareActionReq struct {
	Kind string `path:"kind"`
	Id   int64  `path:"id"`
}

type ShareItem struct {
	Kind       string `json:"kind"`
	Id         int64  `json:"id"`
	SourceName string `json:"sourceName"`
	ShareName  string `json:"shareName"`
	ShareToken string `json:"shareToken"`
	Url        string `json:"url"`
	ExpiresAt  string `json:"expiresAt"`
	Expired    bool   `json:"expired"`
	Enabled    bool   `json:"enabled"`
	Revoked    bool   `json:"revoked"`
}

type ShareListResp struct {
	Items []ShareItem `json:"items"`
}

type ShareTokenReq struct {
	Token  string `path:"token"`
	Target string `form:"target,optional"`
	Filter string `form:"filter,optional"`
}

type ShareUpdateReq struct {
	Kind      string `path:"kind"`
	Id        int64  `path:"id"`
	ShareName string `json:"shareName,optional"`
	ExpiresAt string `json:"expiresAt,optional"`
}

type Status struct {
	Status  string `json:"status"`
	Version string `json:"version"`
	Pid     int    `json:"pid"`
}

type SubFile struct {
	Id                 int64  `json:"id"`
	Name               string `json:"name"`
	Content            string `json:"content"`
	Type               string `json:"type"`
	SyncUrl            string `json:"syncUrl"`
	SourceMode         string `json:"sourceMode"`
	MergeSources       string `json:"mergeSources"`
	IgnoreFailedRemote string `json:"ignoreFailedRemote"`
	UserAgent          string `json:"userAgent"`
	ShareToken         string `json:"shareToken"`
	ConfigType         string `json:"configType"`
	SourceType         string `json:"sourceType"`
	SourceId           int64  `json:"sourceId"`
	TemplateLang       string `json:"templateLang"`
	TrafficUrl         string `json:"trafficUrl"`
	ShareName          string `json:"shareName"`
	ExpiresAt          string `json:"expiresAt"`
}

type SubFileReq struct {
	Name               string `json:"name"`
	Content            string `json:"content,optional"`
	Type               string `json:"type,optional,default=raw"`
	SyncUrl            string `json:"syncUrl,optional"`
	SourceMode         string `json:"sourceMode,optional,default=local"`
	MergeSources       string `json:"mergeSources,optional"`
	IgnoreFailedRemote string `json:"ignoreFailedRemote,optional"`
	UserAgent          string `json:"userAgent,optional"`
	ConfigType         string `json:"configType,optional,default=file"`
	SourceType         string `json:"sourceType,optional"`
	SourceId           int64  `json:"sourceId,optional"`
	TemplateLang       string `json:"templateLang,optional,default=gotemplate"`
	TrafficUrl         string `json:"trafficUrl,optional"`
}

type SubFileUpdateReq struct {
	Id                 int64   `path:"id"`
	Name               *string `json:"name,optional"`
	Content            *string `json:"content,optional"`
	Type               *string `json:"type,optional"`
	SyncUrl            *string `json:"syncUrl,optional"`
	SourceMode         *string `json:"sourceMode,optional"`
	MergeSources       *string `json:"mergeSources,optional"`
	IgnoreFailedRemote *string `json:"ignoreFailedRemote,optional"`
	UserAgent          *string `json:"userAgent,optional"`
	ConfigType         *string `json:"configType,optional"`
	SourceType         *string `json:"sourceType,optional"`
	SourceId           *int64  `json:"sourceId,optional"`
	TemplateLang       *string `json:"templateLang,optional"`
	TrafficUrl         *string `json:"trafficUrl,optional"`
}

type Subscription struct {
	Id           int64              `json:"id"`
	Name         string             `json:"name"`
	Url          string             `json:"url"`
	Content      string             `json:"content"`
	Enabled      bool               `json:"enabled"`
	Interval     int                `json:"interval"`
	Status       string             `json:"status"`
	ErrorMessage string             `json:"errorMessage"`
	LastUpdate   string             `json:"lastUpdate"`
	NodeCount    int                `json:"nodeCount"`
	UserAgent    string             `json:"userAgent"`
	Operators    []PipelineOperator `json:"operators"`
	ShareToken   string             `json:"shareToken"`
	Traffic      *TrafficInfo       `json:"traffic"`
}

type TaskItem struct {
	Id      int64  `json:"id"`
	Name    string `json:"name"`
	Cron    string `json:"cron"`
	Enabled bool   `json:"enabled"`
	LastRun string `json:"lastRun"`
	NextRun string `json:"nextRun"`
	Status  string `json:"status"`
	Message string `json:"message"`
}

type TrafficInfo struct {
	Upload   int64  `json:"upload"`
	Download int64  `json:"download"`
	Used     int64  `json:"used"`
	Total    int64  `json:"total"`
	Expire   int64  `json:"expire"`
	ExpireAt string `json:"expireAt"`
}

type TransparentEnvReport struct {
	OS                  string                  `json:"os"`
	Arch                string                  `json:"arch"`
	Kernel              string                  `json:"kernel"`
	Distro              string                  `json:"distro"`
	PackageManager      string                  `json:"packageManager"`
	Root                bool                    `json:"root"`
	CapNetAdmin         bool                    `json:"capNetAdmin"`
	CapNetRaw           bool                    `json:"capNetRaw"`
	CapNetAdminBounding bool                    `json:"capNetAdminBounding"`
	InContainer         bool                    `json:"inContainer"`
	HostNetwork         bool                    `json:"hostNetwork"`
	TunDevice           string                  `json:"tunDevice"`
	Modes               []TransparentModeStatus `json:"modes"`
	Warnings            []string                `json:"warnings"`
}

type TransparentModeStatus struct {
	Mode        string   `json:"mode"`
	Available   bool     `json:"available"`
	Reason      string   `json:"reason"`
	Missing     []string `json:"missing"`
	InstallHint string   `json:"installHint"`
}

type TransparentProvisionReq struct {
	InstallPackages bool `json:"installPackages,optional"`
	ApplySysctl     bool `json:"applySysctl,optional"`
}

type TransparentProvisionResp struct {
	Success        bool                       `json:"success"`
	Message        string                     `json:"message"`
	Steps          []TransparentProvisionStep `json:"steps"`
	NotPersistent  bool                       `json:"notPersistent"`
	ManualCommands []string                   `json:"manualCommands"`
	Env            TransparentEnvReport       `json:"env"`
}

type TransparentProvisionStep struct {
	Name    string `json:"name"`
	Command string `json:"command"`
	Success bool   `json:"success"`
	Detail  string `json:"detail"`
	Skipped bool   `json:"skipped"`
}

type TransparentStatusResp struct {
	Enabled            bool                 `json:"enabled"`
	Mode               string               `json:"mode"`
	PendingConfirm     bool                 `json:"pendingConfirm"`
	SecondsLeft        int                  `json:"secondsLeft"`
	TProxyPort         int                  `json:"tproxyPort"`
	TUNStack           string               `json:"tunStack"`
	PortConfiguredOnly bool                 `json:"portConfiguredOnly"`
	Env                TransparentEnvReport `json:"env"`
}

type TransparentUpdateReq struct {
	Enabled    bool   `json:"enabled"`
	Mode       string `json:"mode"`
	TProxyPort int    `json:"tproxyPort,optional"`
	TUNStack   string `json:"tunStack,optional"`
}

type UpdateBaseConfigReq struct {
	Content string `json:"content"`
}

type UpdateSettings struct {
	AutoUpdateEnabled bool     `json:"autoUpdateEnabled"`
	AutoUpdateCron    string   `json:"autoUpdateCron"`
	CDNProviders      []string `json:"cdnProviders"`
	UseMihomoProxy    bool     `json:"useMihomoProxy"`
	MihomoProxyUrl    string   `json:"mihomoProxyUrl"`
	MihomoPath        string   `json:"mihomoPath"`
	ZashboardDir      string   `json:"zashboardDir"`
	MihomoPresent     bool     `json:"mihomoPresent"`
	ZashboardPresent  bool     `json:"zashboardPresent"`
	MihomoVersion     string   `json:"mihomoVersion"`
	ZashboardVersion  string   `json:"zashboardVersion"`
	DefaultCDN        []string `json:"defaultCDN"`
	LogRetentionDays  int      `json:"logRetentionDays"`
	LogCleanupCron    string   `json:"logCleanupCron"`
	LogCleanupEnabled bool     `json:"logCleanupEnabled"`
}

type UpdateSettingsReq struct {
	AutoUpdateEnabled *bool    `json:"autoUpdateEnabled,optional"`
	AutoUpdateCron    string   `json:"autoUpdateCron,optional"`
	CDNProviders      []string `json:"cdnProviders,optional"`
	UseMihomoProxy    *bool    `json:"useMihomoProxy,optional"`
	LogRetentionDays  *int     `json:"logRetentionDays,optional"`
	LogCleanupCron    string   `json:"logCleanupCron,optional"`
	LogCleanupEnabled *bool    `json:"logCleanupEnabled,optional"`
}

type UpdateSubscriptionReq struct {
	Id        int64              `path:"id"`
	Name      string             `json:"name,optional"`
	Url       *string            `json:"url,optional"`
	Content   *string            `json:"content,optional"`
	UserAgent *string            `json:"userAgent,optional"`
	Enabled   *bool              `json:"enabled,optional"`
	Interval  int                `json:"interval,optional"`
	Operators []PipelineOperator `json:"operators,optional"`
}
